// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Server_API.Migrations
{
    [DbContext(typeof(UserDBContext))]
    [Migration("20240520140105_InitUser")]
    partial class InitUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("Server_API.Models.PW", b =>
                {
                    b.Property<string>("salt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ID_KhachHang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("salt");

                    b.HasIndex("ID_KhachHang")
                        .IsUnique();

                    b.ToTable("KhongPhaiMatKhau", (string)null);
                });

            modelBuilder.Entity("Server_API.Models.User", b =>
                {
                    b.Property<string>("ID_KhachHang")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NamSinh")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.HasKey("ID_KhachHang");

                    b.ToTable("khachhang", (string)null);
                });

            modelBuilder.Entity("Server_API.Models.PW", b =>
                {
                    b.HasOne("Server_API.Models.User", "User")
                        .WithOne("PW")
                        .HasForeignKey("Server_API.Models.PW", "ID_KhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server_API.Models.User", b =>
                {
                    b.Navigation("PW")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
